FROM python:3.9

WORKDIR /var/www

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
EXPOSE 8000

COPY . ./

RUN pip3 install --no-cache-dir --upgrade -r /var/www/requirements.txt && \
    python3 manage.py makemigrations && \
    python3 manage.py migrate && python3 upload_data_to_db.py

CMD ["python3", "manage_dev.py", "runserver", "0.0.0.0:8000"]