# Generated by Django 4.1 on 2022-08-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_id', models.IntegerField()),
                ('original_crime_type_name', models.TextField()),
                ('report_date', models.DateTimeField(db_index=True)),
                ('call_date', models.DateTimeField()),
                ('offense_date', models.DateTimeField()),
                ('call_time', models.DateTimeField()),
                ('call_date_time', models.DateTimeField()),
                ('disposition', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField(null=True)),
                ('state', models.TextField()),
                ('agency_id', models.IntegerField()),
                ('address_type', models.TextField()),
                ('common_location', models.TextField(null=True)),
            ],
        ),
    ]
